### ISSUE TITLE
can not apply if branch name contain "/"

### ISSUE THREAD

**Issue by wuzechen** [plus3it/terraform-aws-codecommit-flow-ci#80]
if branch name contain "/", apply will fail.

ERROR INFO:
`│ Error: invalid value for name (must match [\w+=,.@-])`

Reason in code 
` stage             = "branch-${var.branch}"`
` name_slug     = "${var.repo_name}-${var.stage}-flow-ci"`
```
/modules/_internal/runner/main.tf line 104, in resource "aws_iam_role_policy" "codebuild":
│  104:   name   = "${local.name_slug}-codebuild"
```

can fix it by add replace function like
` stage             = "branch-${replace(var.branch, '/[OR OTHER NEED ESCAPE CHAR]', '')}"`

**Comment by lorengordon** [comment]
@wuzechen oh that makes sense. I'm on holiday for a bit, so won't be able to get to it myself. Would you be willing to open a pull request with that change and maybe adjust/add a test config to exercise it?
