### ISSUE TITLE
Update value for Lambda runtime in modules/_internal/handler

### ISSUE THREAD

**Issue by jebbens** [plus3it/terraform-aws-codecommit-flow-ci#88]
The value for the `runtime` variable specified in modules/_internal/handler, which is "python3.6" should be updated to "python3.9" or made a variable with a default value of "python3.9". The python 3.6 runtime has been deprecated in Lambda.

**Comment by lorengordon** [comment]
Sure we can add a variable. `nullable = false` makes it easy, so we can specify the default only in the handler, and everywhere else it can be passed as `null`.

**Comment by lorengordon** [comment]
Thanks for reporting the issue @jebbens! This should be released in v4.4.0 shortly!

**Comment by jebbens** [comment]
Wow, that was fast - thanks so much!
